{% set name = "feedgenerator" %}
{% set version = "2.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/feedgenerator-{{ version }}.tar.gz
  sha256: 2976f6ccc5989a967202da343ea145c21aedabbe0035c7088d64ba0aa9725a60

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - tzdata  # [win]

test:
  imports:
    - feedgenerator
    - feedgenerator.django
    - feedgenerator.django.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/getpelican/feedgenerator
  summary: Standalone version of django.utils.feedgenerator
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - moorepants
