{% set version = "1.9.1" %}

package:
  name: feedgenerator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/feedgenerator/feedgenerator-{{ version }}.tar.gz
  sha256: a28a5add781509390d1a6a52d017829853ee4bef1d2e7b4d5da0e9d1b395ce54

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytz
    - six

test:
  imports:
    - feedgenerator
    - feedgenerator.django
    - feedgenerator.django.utils

about:
  home: https://github.com/dmdm/feedgenerator-py3k.git
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Standalone version of django.utils.feedgenerator, compatible with Py3k

extra:
  recipe-maintainers:
    - ocefpaf
    - moorepants
