{% set version = "1.9" %}

package:
    name: feedgenerator
    version: {{ version }}

source:
    fn: feedgenerator-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/f/feedgenerator/feedgenerator-{{ version }}.tar.gz
    md5: f542f4098dbb5c63a94c88cbfc727778

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pytz
        - six

test:
    imports:
        - feedgenerator
        - feedgenerator.django
        - feedgenerator.django.utils

about:
    home: https://github.com/dmdm/feedgenerator-py3k.git
    license: BSD-3-Clause
    summary: Standalone version of django.utils.feedgenerator, compatible with Py3k

extra:
    recipe-maintainers:
        - ocefpaf
        - moorepants
