{% set version = "2.0.0" %}

package:
  name: feedgenerator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/feedgenerator/feedgenerator-{{ version }}.tar.gz
  sha256: 6836d456b8b0edbc5b6d3a42d1be852cebd43d2f28af4ff51789eb295f1860e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytz
    - six

test:
  imports:
    - feedgenerator
    - feedgenerator.django
    - feedgenerator.django.utils

about:
  home: https://github.com/dmdm/feedgenerator-py3k.git
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Standalone version of django.utils.feedgenerator, compatible with Py3k

extra:
  recipe-maintainers:
    - ocefpaf
    - moorepants
