travis:
  secure:
    BINSTAR_TOKEN: OoKJeFTNI2fk25gXDc6AKgwk7v54O0LlTkOkkZO9d79rp2jfz4k5rZFhQzjMY3zzB9Hnsn83f1cxteNxn4H99gKJ9Ibe0r2Qb41WdZn/EPTV3qSKVI9G5VP7aEevFwGZt28h1MS9yCQf4o9SRog2VyiK09hWYbw3tY+s322xakf8x2XdghNTLI6hR3f7lmMUJ37TVjcvXxKojEOOWoE4ixH7kJJvPPaS7Ik9E5XT4teJzfM733ILGlNbrTeNRCd3ujft7HTYqbCj0iSnTuYIcGEC6/1lShcqvdbuFCDMMNFmo+JyXjfbvbySFnkV9WUuhoc31VEyQ4Q5LRsPaulvY0g5WOMcz+eQmgbYM1X7icrLuvHemfc3SCJjCWBlMlxxqda55kEXtBzCty194XGzXno7ED+h8KvUk/Q2qBRlJy6yCczHvz/S4pBwigj8Ez4srbjLX/QZGiuW5+aO5sHTGHl/g6Z7fYoKaiXp2j1gL6BgRMBPEYRZV9f75bsPo23FCiKH2x+nbZkC06e5aXI9xu4SpNY3Rhp3Oz1SVCRkEQGuS/TmH3D7DuDqxNP9VjOTj31m4vnNS6gA508bAKvuR1usoAILmY63zPBd08G8StIaZYr1re3tfUVgbxJXsrmCY9QIJTs5DN4oIeQGd0Euf77eOOoud17grDIl+yFYp9A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
