travis:
  secure:
    BINSTAR_TOKEN: ez8qPbPjkDiVa8j7vil1Uo9r/g8Eeu5ZHwyB8hzvpdfcy6zGwZ1iWj2vbF+cuse+GoC0v5e7Ewic5FD6lxwaY0WUxJo+czQnuWnCXM9KbLtgMySGYdQboqXBYVS2piKesKWLRtwDchtSy383ZeZlWp1q6mttyW6vu75VjmZ+3MqViV/MCEtSJBxKxtlgpQtoMYFCUVrNfBI9UI3NTq42u3szhDeLUYXEijTnUGNc3K2M1oO1HiT8YdYvHS7vdAXLVUu+D0uvcoF5qr+vyFf67X2wd/yULDI7bGCgrWIHw+ZdNFvDoIOQconm56VPQzlGIrkSGxnutGamtqBLERrUnJOrRpXRBE+ieG5V4vA+EtTpPPkbVRFTKLbQ/XYaQpnTv9KFmANudnkf4WMhMD+Tee++2JFcS5QteHwe7/v6uxcUT0chUGMw1b2azFRgAXMXWKzmCK8Be4JoeKZKWOxKpcb58MQV84IglP6xTCYGsDg+7O9y0Fs38xfzB4UNTiLcxT46VIclYd7GRplXauPDUjcGhQt0LnC2ypWRfNqD6NYL3Zt0CFrnI5W7QuQ/Y+soRGzrFi1BnBn4P7YHiIQ2+iH8l3xRmbOUJfuzmRwuJcQsFmOrz+FELebp5g6wQj30crKWy5tt0yKvq0leCaznB5JtMc2Rf4k0GIiSdfXm9b4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
